Repository globus/globus-sdk-python, pull requests merged in 2022-06, with the labels that each got.

#581 Remove doc references to 'scopes' field in Auth
  docs/examples/client_credentials.rst
  docs/examples/three_legged_oauth.rst
Labels: docs, no-news-is-good-news

#584 Improve testing subpackage with more responses support and inherited metadata
  setup.py
  src/globus_sdk/_testing/README.rst
  src/globus_sdk/_testing/data/auth/oauth2_userinfo.py
  src/globus_sdk/_testing/data/globus_connect_server/create_storage_gateway.py
  src/globus_sdk/_testing/data/globus_connect_server/create_user_credential.py
  src/globus_sdk/_testing/data/globus_connect_server/delete_storage_gateway.py
  src/globus_sdk/_testing/data/globus_connect_server/delete_user_credential.py
  src/globus_sdk/_testing/data/globus_connect_server/get_storage_gateway.py
  src/globus_sdk/_testing/data/globus_connect_server/get_storage_gateway_list.py
  src/globus_sdk/_testing/data/globus_connect_server/get_user_credential.py
  src/globus_sdk/_testing/data/globus_connect_server/update_storage_gateway.py
  src/globus_sdk/_testing/data/globus_connect_server/update_user_credential.py
  src/globus_sdk/_testing/data/groups/delete_group.py
  src/globus_sdk/_testing/data/groups/get_group.py
  src/globus_sdk/_testing/data/groups/get_my_groups.py
  src/globus_sdk/_testing/data/search/delete_role.py
  src/globus_sdk/_testing/data/search/get_role_list.py
  src/globus_sdk/_testing/data/search/post_search.py
  src/globus_sdk/_testing/data/search/search.py
  src/globus_sdk/_testing/data/timer/delete_job.py
  src/globus_sdk/_testing/data/timer/get_job.py
  src/globus_sdk/_testing/data/timer/list_jobs.py
  src/globus_sdk/_testing/data/timer/update_job.py
  src/globus_sdk/_testing/models.py
  tests/unit/test_paging.py
Labels: maintenance, no-news-is-good-news

#585 Add `_testing.data.transfer.get_endpoint` module
  src/globus_sdk/_testing/data/transfer/__init__.py
  src/globus_sdk/_testing/data/transfer/get_endpoint.py
Labels: no-news-is-good-news

#586 Update get_endpoint test to use _testing
  tests/functional/transfer/fixture_data/get_endpoint_goep1.json
  tests/functional/transfer/fixture_data/get_endpoint_goep2.json
  tests/functional/transfer/test_simple.py
Labels: maintenance, no-news-is-good-news

#588 Convert {create,update}_endpoint test fixtures
  src/globus_sdk/_testing/data/transfer/create_endpoint.py
  src/globus_sdk/_testing/data/transfer/update_endpoint.py
  tests/functional/transfer/fixture_data/ep_create.json
  tests/functional/transfer/fixture_data/ep_update.json
  tests/functional/transfer/test_simple.py
Labels: maintenance, no-news-is-good-news
